### Get All Posts
GET http://localhost:4040/api/v1/posts

### Create a New Post
POST http://localhost:4040/api/v1/posts
Content-Type: application/json

{
  "title": "My First API Post",
  "content": "Testing Sequelize with MySQL and REST client!",
  "tags": ["api", "mysql", "test"]
}

### Update existing post
PUT http://localhost:4040/api/v1/posts/2
Content-Type: application/json

{
  "id": 2,
  "title": "Second Post Now",
  "content": "Happy that i am getting it right now!",
  "category": "Love",
  "tags": ["happiness", "joy", "work"]
}
